export const SHOW_MODAL_STOCK = 'SHOW_MODAL_STOCK';
export const SHOW_MODAL_LOADING = 'SHOW_MODAL_LOADING';
export const CHANGE_AMOUNT_HOME = 'CHANGE_AMOUNT_HOME';
export const CHANGE_DATE_HOME = 'CHANGE_DATE_HOME';
export const CHANGE_INVESTMENT_HOME = 'CHANGE_INVESTMENT_HOME';
export const UPDATE_DATA_INVESTMENT_HOME = 'UPDATE_DATA_INVESTMENT_HOME';

export const CHANGE_AMOUNT_PORTFOLIO = 'CHANGE_AMOUNT_PORTFOLIO';
export const CHANGE_DATE_PORTFOLIO = 'CHANGE_DATE_PORTFOLIO';
export const ADD_INVESTMENT_PORTFOLIO = 'ADD_INVESTMENT_PORTFOLIO';
export const REMOVE_INVESTMENT_PORTFOLIO = 'REMOVE_INVESTMENT_PORTFOLIO';
export const SHOW_MODAL_PORTFOLIO = 'SHOW_MODAL_PORTFOLIO';
export const CHANGE_PERCENTAGE = 'CHANGE_PERCENTAGE';
export const UPDATE_DATA_PORTFOLIO = 'UPDATE_DATA_PORTFOLIO';
export const CHANGE_SELECTED_PORTFOLIO = 'CHANGE_SELECTED_PORTFOLIO';
